name: Cleanup untagged Docker images

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ 'Label pushed Docker Images' ]
    types:
      - completed

jobs:
  image-cleanup:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success')
    steps:
      - name: Delete untagged Docker images
        uses: Chizkiyahu/delete-untagged-ghcr-action@707cf4f1445ec3e3f5c7bfc83a023fb868cd1174 # v6.1.1
        with:
          token: ${{ secrets.GHCR_DELETE_PACKAGE_TOKEN }}
          repository_owner: ${{ github.repository_owner }}
          repository: ${{ github.repository }}
          untagged_only: true
          owner_type: org
          except_untagged_multiplatform: true
